const DATA = {
  ru: {
    locale:'ru-RU', title:'Газиз Абишев — политолог', description:'Газиз Абишев — казахстанский политолог, политический обозреватель, ведущий и Visiting Fellow Оксфордского университета.',
    nav:[['about','Обо мне'],['education','Образование'],['experience','Опыт'],['public','Общественная деятельность'],['research','Исследования'],['media','Медиа'],['awards','Награды'],['contact','Контакты']], menu:'Меню',
    hero:{eyebrow:'Астана, Казахстан',name:'Газиз Абишев',lead:'Политолог, политический обозреватель и телеведущий',note:'Политический обозреватель Jibek Joly TV, автор ABISHEV ANALYTICS и Visiting Fellow Оксфордского университета (2025–2026).',about:'Обо мне',research:'Публикации'},
    about:{k:'Профиль',h:'Обо мне',intro:'Академические исследования, экспертная работа и публичная политическая аналитика.',p1:'Газиз Абишев — казахстанский политолог, исследователь и политический обозреватель. Специализируется на изучении делиберативной демократии, эволюции политического режима, внутриполитических процессов и внешней политики Казахстана.',p2:'Совмещает академические исследования с экспертной, общественной и медийной деятельностью. В 2025–2026 годах являлся приглашённым исследователем Центра Низами Гянджеви Оксфордского университета.',facts:[['Полное имя','Газиз Серикович Абишев'],['Дата рождения','5 сентября 1984'],['Место рождения','Карагандинская область, Казахстан'],['Гражданство','Казахстан'],['Место работы','Астана, Казахстан']],spec:['Делиберативная демократия','Policy advisory councils и systems','Политические процессы Казахстана','Внешняя политика Казахстана']},
    education:{k:'Квалификация',h:'Образование',intro:'Междисциплинарная подготовка в политологии, экономике и математике.',items:[['2022–2025','ЕНУ имени Л. Н. Гумилёва','Докторская программа по политологии завершена; степень ожидается после защиты диссертации.'],['2015–2016','Queen Mary University of London','Магистр экономики (MSc Economics).'],['2006–2008','Алматинская академия экономики и статистики','Бакалавр экономики.'],['2001–2007','Павлодарский государственный педагогический институт','Магистр математики (2005–2007); бакалавр математики (2001–2005).']]},
    experience:{k:'Карьера',h:'Профессиональный опыт',intro:'От преподавания математики и деловой журналистики до государственной аналитики, телевидения и академических исследований.',items:[['2025–2026','University of Oxford','Visiting Fellow, Oxford Nizami Ganjavi Centre, Faculty of Asian and Middle Eastern Studies.'],['2023 — н.в.','Jibek Joly TV','Политический обозреватель.'],['2018–2024','Turan Times','Основатель и главный редактор.'],['2016–2018','Министерство по инвестициям и развитию РК','Внештатный советник вице-министра.'],['2014–2015','Служба центральных коммуникаций при Президенте РК','Аналитик.'],['2013–2015','Oilnews Kazakhstan','Главный редактор информационного агентства.'],['2012–2013','«Седьмой канал»','Корреспондент отдела экономики и политики.'],['2009–2012','Деловой еженедельник «Курсив»','Заместитель главного редактора.'],['2005–2009','Гимназия №3 для одарённых детей, Павлодар','Учитель математики.']]},
    public:{k:'Государство и общество',h:'Общественная деятельность',intro:'Участие в ключевых консультативных и экспертных площадках Республики Казахстан.',items:[['2026','Член Конституционной комиссии Республики Казахстан'],['2025–2026','Член Национального курултая при Президенте Республики Казахстан'],['2022–2026','Член Общественной палаты при Мажилисе Парламента Республики Казахстан'],['2020–2023','Член Клуба экспертов при Сенате Парламента Республики Казахстан']]},
    research:{k:'Академическая работа',h:'Исследования и публикации',intro:'Избранные рецензируемые статьи о политических трансформациях, идентичности и механизмах делиберативной демократии.',publications:[['2026','From Margins to Mainstream: National-Patriots and Kazakhisation in the Making of Post-Nazarbayev Kazakhstan','Bakhytzhan Kurmanov, Gaziz Abishev','Asian Affairs, 57(2), 299–330','https://doi.org/10.1080/03068374.2025.2605288'],['2024','Authoritarian Succession, Rules, and Conflicts: Tokayev’s Gambit and Kazakhstan’s Bloody January of 2022 (Qandy Qantar)','Gaziz Abishev, Bakhytzhan Kurmanov, Zhaxylyk Sabitov','Post-Soviet Affairs, 40(6), 429–451','https://doi.org/10.1080/1060586X.2024.2377929'],['2023','Онлайн-петиции как фрейм делиберативной демократии в современном Казахстане','Газиз Абишев, Елена Нечаева','Казахстан-Спектр, 105(1)','https://doi.org/10.52536/2415-8216.2023-1.01'],['2022','Национальный совет общественного доверия как механизм реализации делиберативной демократии','Газиз Абишев','Казахстан-Спектр, 102(2)','https://doi.org/10.52536/2415-8216.2022-2.01']],doi:'Открыть DOI',reportLabel:'Авторский аналитический доклад',report:'Политический аспект работы Национального курултая',reportMeta:'Казахстанский институт общественного развития, Астана, 2023. 100 с. ISBN 978-9965-23-630-3.',reportLink:'Читать доклад',scholar:'Все публикации в Google Scholar'},
    media:{k:'Авторские проекты',h:'Медиа',intro:'Регулярная аналитика о политике Казахстана и международных отношениях.',items:[['ABISHEV ANALYTICS','Авторский Telegram-канал: политическая аналитика и комментарии.','Telegram','https://t.me/gaziz1984'],['НеКурултай','Основатель, автор и ведущий YouTube-проекта с дискуссиями о политике, обществе и экономике.','YouTube','https://www.youtube.com/@NeQuryltay'],['Талдау','Ведущий аналитической программы Jibek Joly TV об актуальных событиях в Казахстане и мире.','Jibek Joly','https://jjtv.kz/ru/programms/taldau-rus']]},
    awards:{k:'Признание',h:'Награды',intro:'Государственные, профессиональные и общественные награды.',items:[['2026','Орден «Құрмет»','Государственная награда Республики Казахстан.'],['2026','«Қазақстан Республикасының Парламентіне 30 жыл»','Юбилейная медаль за вклад в развитие парламентаризма.'],['2022','Медаль «Ерен еңбегі үшін»','Государственная награда Республики Казахстан.'],['2024','Национальная премия «Үркер»','«НеКурултай» — лучший подкаст года.'],['2024','«Халықтың сүйіктісі — Народный любимец»','Победитель в номинации «Политолог года»; вручение в январе 2025 года.']]},
    skills:{k:'Дополнительно',h:'Языки и обучение',languages:'Языки',training:'Дополнительное обучение',langs:[['Казахский','B1, QAZTEST — 166 баллов, 2024'],['Русский','Свободное владение'],['Английский','IELTS Academic 7.0, 2024']],courses:[['2014','Мобильная журналистика','Thomson Reuters Foundation, Лондон'],['2006','Инновационные технологии в преподавании математики','София, Болгария'],['2004','Летняя школа демократии','Фонд имени Фридриха Эберта, Берлин']]},
    contact:{k:'Профессиональные профили',h:'Контакты',intro:'Для запросов на интервью, выступления и экспертные комментарии.',location:'Астана, Казахстан',note:'Связаться можно через Telegram или LinkedIn.',cv:'Скачать CV',cvnote:'Русская и английская версии CV будут добавлены после финальной проверки сайта.'},footer:'© 2026 Газиз Абишев. Персональный сайт.'
  },
  kk: {
    locale:'kk-KZ', title:'Ғазиз Әбішев — саясаттанушы', description:'Ғазиз Әбішев — қазақстандық саясаттанушы, саяси шолушы, тележүргізуші және Оксфорд университетінің Visiting Fellow зерттеушісі.',
    nav:[['about','Мен туралы'],['education','Білім'],['experience','Тәжірибе'],['public','Қоғамдық қызмет'],['research','Зерттеулер'],['media','Медиа'],['awards','Марапаттар'],['contact','Байланыс']],menu:'Мәзір',
    hero:{eyebrow:'Астана, Қазақстан',name:'Ғазиз Әбішев',lead:'Саясаттанушы, саяси шолушы және тележүргізуші',note:'Jibek Joly телеарнасының саяси шолушысы, ABISHEV ANALYTICS авторы және Оксфорд университетінің Visiting Fellow зерттеушісі (2025–2026).',about:'Мен туралы',research:'Жарияланымдар'},
    about:{k:'Профиль',h:'Мен туралы',intro:'Академиялық зерттеулер, сарапшылық жұмыс және қоғамдық-саяси талдау.',p1:'Ғазиз Әбішев — қазақстандық саясаттанушы, зерттеуші және саяси шолушы. Делиберативті демократияны, саяси режим эволюциясын, Қазақстандағы ішкі саяси үдерістер мен сыртқы саясатты зерттейді.',p2:'Академиялық зерттеулерді сарапшылық, қоғамдық және медиалық қызметпен ұштастырады. 2025–2026 жылдары Оксфорд университетінің Низами Гәнжауи орталығында шақырылған зерттеуші болды.',facts:[['Толық аты-жөні','Әбішев Ғазиз Серікұлы'],['Туған күні','1984 жылғы 5 қыркүйек'],['Туған жері','Қазақстан, Қарағанды облысы'],['Азаматтығы','Қазақстан Республикасы'],['Қызмет ететін қаласы','Астана, Қазақстан']],spec:['Делиберативті демократия','Policy advisory councils және systems','Қазақстандағы саяси үдерістер','Қазақстанның сыртқы саясаты']},
    education:{k:'Біліктілік',h:'Білім',intro:'Саясаттану, экономика және математика салаларындағы пәнаралық білім.',items:[['2022–2025','Л.Н. Гумилев атындағы Еуразия ұлттық университеті','Саясаттану бойынша докторлық бағдарлама аяқталды; дәреже диссертация қорғалғаннан кейін беріледі.'],['2015–2016','Queen Mary University of London','Экономика магистрі (MSc Economics).'],['2006–2008','Алматы экономика және статистика академиясы','Экономика бакалавры.'],['2001–2007','Павлодар мемлекеттік педагогикалық институты','Математика магистрі (2005–2007); математика бакалавры (2001–2005).']]},
    experience:{k:'Мансап',h:'Кәсіби тәжірибе',intro:'Математика мұғалімі мен іскерлік журналистикадан мемлекеттік талдау, телевидение және академиялық зерттеулерге дейін.',items:[['2025–2026','University of Oxford','Visiting Fellow, Oxford Nizami Ganjavi Centre, Faculty of Asian and Middle Eastern Studies.'],['2023 — қазіргі уақыт','Jibek Joly TV','Саяси шолушы.'],['2018–2024','Turan Times','Құрылтайшысы және бас редакторы.'],['2016–2018','ҚР Инвестициялар және даму министрлігі','Вице-министрдің штаттан тыс кеңесшісі.'],['2014–2015','ҚР Президенті жанындағы Орталық коммуникациялар қызметі','Талдаушы.'],['2013–2015','Oilnews Kazakhstan','Ақпарат агенттігінің бас редакторы.'],['2012–2013','«Жетінші арна»','Экономика және саясат бөлімінің тілшісі.'],['2009–2012','«Курсив» іскерлік апталығы','Бас редактордың орынбасары.'],['2005–2009','Дарынды балаларға арналған №3 гимназия, Павлодар','Математика мұғалімі.']]},
    public:{k:'Мемлекет және қоғам',h:'Қоғамдық қызмет',intro:'Қазақстан Республикасының негізгі консультативтік және сарапшылық алаңдарына қатысу.',items:[['2026','Қазақстан Республикасы Конституциялық комиссиясының мүшесі'],['2025–2026','Қазақстан Республикасы Президенті жанындағы Ұлттық құрылтай мүшесі'],['2022–2026','Қазақстан Республикасы Парламенті Мәжілісі жанындағы Қоғамдық палата мүшесі'],['2020–2023','Қазақстан Республикасы Парламенті Сенаты жанындағы Сарапшылар клубының мүшесі']]},
    research:{k:'Академиялық жұмыс',h:'Зерттеулер мен жарияланымдар',intro:'Саяси трансформациялар, бірегейлік және делиберативті демократия тетіктері туралы таңдамалы рецензияланған мақалалар.',publications:[['2026','From Margins to Mainstream: National-Patriots and Kazakhisation in the Making of Post-Nazarbayev Kazakhstan','Bakhytzhan Kurmanov, Gaziz Abishev','Asian Affairs, 57(2), 299–330','https://doi.org/10.1080/03068374.2025.2605288'],['2024','Authoritarian Succession, Rules, and Conflicts: Tokayev’s Gambit and Kazakhstan’s Bloody January of 2022 (Qandy Qantar)','Gaziz Abishev, Bakhytzhan Kurmanov, Zhaxylyk Sabitov','Post-Soviet Affairs, 40(6), 429–451','https://doi.org/10.1080/1060586X.2024.2377929'],['2023','Онлайн-петиции как фрейм делиберативной демократии в современном Казахстане','Газиз Абишев, Елена Нечаева','Казахстан-Спектр, 105(1)','https://doi.org/10.52536/2415-8216.2023-1.01'],['2022','Национальный совет общественного доверия как механизм реализации делиберативной демократии','Газиз Абишев','Казахстан-Спектр, 102(2)','https://doi.org/10.52536/2415-8216.2022-2.01']],doi:'DOI ашу',reportLabel:'Авторлық аналитикалық баяндама',report:'Ұлттық құрылтай жұмысының саяси аспектісі',reportMeta:'Қазақстандық қоғамдық даму институты, Астана, 2023. 100 бет. ISBN 978-9965-23-630-3.',reportLink:'Баяндаманы оқу',scholar:'Google Scholar-дағы барлық жарияланымдар'},
    media:{k:'Авторлық жобалар',h:'Медиа',intro:'Қазақстан саясаты мен халықаралық қатынастар туралы тұрақты талдау.',items:[['ABISHEV ANALYTICS','Саяси талдау мен түсініктемелерге арналған авторлық Telegram-арна.','Telegram','https://t.me/gaziz1984'],['НеКурултай','Саясат, қоғам және экономика туралы пікірталастарға арналған YouTube-жобаның негізін қалаушысы, авторы және жүргізушісі.','YouTube','https://www.youtube.com/@NeQuryltay'],['Талдау','Қазақстан мен әлемдегі өзекті оқиғалар туралы Jibek Joly сараптамалық бағдарламасының жүргізушісі.','Jibek Joly','https://jjtv.kz/ru/programms/taldau-rus']]},
    awards:{k:'Мойындау',h:'Марапаттар',intro:'Мемлекеттік, кәсіби және қоғамдық марапаттар.',items:[['2026','«Құрмет» ордені','Қазақстан Республикасының мемлекеттік наградасы.'],['2026','«Қазақстан Республикасының Парламентіне 30 жыл»','Парламентаризмді дамытуға қосқан үлесі үшін мерейтойлық медаль.'],['2022','«Ерен еңбегі үшін» медалі','Қазақстан Республикасының мемлекеттік наградасы.'],['2024','«Үркер» ұлттық сыйлығы','«НеКурултай» — жылдың үздік подкасты.'],['2024','«Халықтың сүйіктісі» ұлттық сыйлығы','«Жыл саясаттанушысы» номинациясының жеңімпазы; марапат 2025 жылғы қаңтарда табысталды.']]},
    skills:{k:'Қосымша',h:'Тілдер және оқу',languages:'Тілдер',training:'Қосымша оқу',langs:[['Қазақ тілі','B1, QAZTEST — 166 балл, 2024'],['Орыс тілі','Еркін меңгерген'],['Ағылшын тілі','IELTS Academic 7.0, 2024']],courses:[['2014','Мобильді журналистика','Thomson Reuters Foundation, Лондон'],['2006','Математиканы оқытудағы инновациялық технологиялар','София, Болгария'],['2004','Демократия жазғы мектебі','Фридрих Эберт қоры, Берлин']]},
    contact:{k:'Кәсіби профильдер',h:'Байланыс',intro:'Сұхбат, баяндама және сараптамалық түсініктеме жөніндегі ұсыныстар үшін.',location:'Астана, Қазақстан',note:'Telegram немесе LinkedIn арқылы байланысуға болады.',cv:'CV жүктеу',cvnote:'CV-дің орыс және ағылшын нұсқалары сайт соңғы тексеруден өткеннен кейін қосылады.'},footer:'© 2026 Ғазиз Әбішев. Жеке сайт.'
  },
  en: {
    locale:'en-GB', title:'Gaziz Abishev — Political Scientist', description:'Gaziz Abishev is a Kazakhstani political scientist, political commentator, talk-show host and former Visiting Fellow at the University of Oxford.',
    nav:[['about','About'],['education','Education'],['experience','Experience'],['public','Public service'],['research','Research'],['media','Media'],['awards','Awards'],['contact','Contact']],menu:'Menu',
    hero:{eyebrow:'Astana, Kazakhstan',name:'Gaziz Abishev',lead:'Political scientist, political commentator and talk-show host',note:'Political commentator at Jibek Joly TV, author of ABISHEV ANALYTICS, and Visiting Fellow at the University of Oxford (2025–2026).',about:'About me',research:'Publications'},
    about:{k:'Profile',h:'About',intro:'Academic research, policy expertise and public political analysis.',p1:'Gaziz Abishev is a Kazakhstani political scientist, researcher and political commentator. His work focuses on deliberative democracy, the evolution of Kazakhstan’s political regime, domestic political processes and Kazakhstan’s foreign policy.',p2:'He combines academic research with policy, civic and media work. In 2025–2026 he was a Visiting Fellow at the Oxford Nizami Ganjavi Centre, University of Oxford.',facts:[['Full name','Gaziz Abishev'],['Date of birth','5 September 1984'],['Place of birth','Karaganda Region, Kazakhstan'],['Citizenship','Kazakhstan'],['Based in','Astana, Kazakhstan']],spec:['Deliberative democracy','Policy advisory councils and systems','Political processes in Kazakhstan','Kazakhstan’s foreign policy']},
    education:{k:'Qualifications',h:'Education',intro:'Interdisciplinary training in political science, economics and mathematics.',items:[['2022–2025','L.N. Gumilyov Eurasian National University','PhD programme in Political Science completed; degree pending dissertation defence.'],['2015–2016','Queen Mary University of London','MSc Economics.'],['2006–2008','Almaty Academy of Economics and Statistics','Bachelor’s degree in Economics.'],['2001–2007','Pavlodar State Pedagogical Institute','MSc Mathematics (2005–2007); Bachelor’s degree in Mathematics (2001–2005).']]},
    experience:{k:'Career',h:'Professional experience',intro:'From mathematics education and business journalism to policy analysis, television and academic research.',items:[['2025–2026','University of Oxford','Visiting Fellow, Oxford Nizami Ganjavi Centre, Faculty of Asian and Middle Eastern Studies.'],['2023–present','Jibek Joly TV','Political commentator.'],['2018–2024','Turan Times','Founder and Editor-in-Chief.'],['2016–2018','Ministry for Investments and Development of Kazakhstan','Non-staff adviser to the Vice Minister.'],['2014–2015','Central Communications Service under the President of Kazakhstan','Analyst.'],['2013–2015','Oilnews Kazakhstan','Editor-in-Chief.'],['2012–2013','Seventh Channel TV','Economics and politics correspondent.'],['2009–2012','Kursiv Business Weekly','Deputy Editor-in-Chief.'],['2005–2009','Gymnasium No. 3 for Gifted Children, Pavlodar','Mathematics teacher.']]},
    public:{k:'State and society',h:'Public service',intro:'Participation in Kazakhstan’s key consultative and expert bodies.',items:[['2026','Member, Constitutional Commission of the Republic of Kazakhstan'],['2025–2026','Member, National Qurultay under the President of Kazakhstan'],['2022–2026','Member, Public Chamber under the Mazhilis of Parliament'],['2020–2023','Member, Experts’ Club under the Senate of Parliament']]},
    research:{k:'Academic work',h:'Research and publications',intro:'Selected peer-reviewed research on political transformation, identity and mechanisms of deliberative democracy.',publications:[['2026','From Margins to Mainstream: National-Patriots and Kazakhisation in the Making of Post-Nazarbayev Kazakhstan','Bakhytzhan Kurmanov, Gaziz Abishev','Asian Affairs, 57(2), 299–330','https://doi.org/10.1080/03068374.2025.2605288'],['2024','Authoritarian Succession, Rules, and Conflicts: Tokayev’s Gambit and Kazakhstan’s Bloody January of 2022 (Qandy Qantar)','Gaziz Abishev, Bakhytzhan Kurmanov, Zhaxylyk Sabitov','Post-Soviet Affairs, 40(6), 429–451','https://doi.org/10.1080/1060586X.2024.2377929'],['2023','Online Petitions as a Framework of Deliberative Democracy in Contemporary Kazakhstan','Gaziz Abishev, Elena Nechayeva','Kazakhstan-Spectrum, 105(1)','https://doi.org/10.52536/2415-8216.2023-1.01'],['2022','The National Council of Public Trust as a Mechanism for Implementing Deliberative Democracy','Gaziz Abishev','Kazakhstan-Spectrum, 102(2)','https://doi.org/10.52536/2415-8216.2022-2.01']],doi:'Open DOI',reportLabel:'Authored analytical report',report:'The Political Dimension of the National Qurultay’s Work',reportMeta:'Kazakhstan Institute of Public Development, Astana, 2023. 100 pp. ISBN 978-9965-23-630-3.',reportLink:'Read report',scholar:'All publications on Google Scholar'},
    media:{k:'Original projects',h:'Media',intro:'Regular analysis of Kazakhstani politics and international affairs.',items:[['ABISHEV ANALYTICS','Author-led Telegram channel featuring political analysis and commentary.','Telegram','https://t.me/gaziz1984'],['NeQurultay','Founder, author and host of a YouTube project featuring discussions on politics, society and economics.','YouTube','https://www.youtube.com/@NeQuryltay'],['Taldau','Host of Jibek Joly TV’s analytical programme on current affairs in Kazakhstan and around the world.','Jibek Joly','https://jjtv.kz/ru/programms/taldau-rus']]},
    awards:{k:'Recognition',h:'Awards',intro:'State, professional and public awards.',items:[['2026','Order of Qurmet','State award of the Republic of Kazakhstan.'],['2026','30 Years of the Parliament of Kazakhstan','Commemorative medal for contribution to the development of parliamentarism.'],['2022','Eren Enbegi Ushin Medal','State award of the Republic of Kazakhstan for distinguished labour.'],['2024','Urker National Award','NeQurultay — Best Podcast of the Year.'],['2024','Halyqtyn Suiiktisi National Award','Political Scientist of the Year; presented in January 2025.']]},
    skills:{k:'Additional',h:'Languages and training',languages:'Languages',training:'Professional development',langs:[['Kazakh','B1, QAZTEST — 166 points, 2024'],['Russian','Full professional proficiency'],['English','IELTS Academic 7.0, 2024']],courses:[['2014','Mobile Journalism','Thomson Reuters Foundation, London'],['2006','Innovative Technologies in Teaching Mathematics','Sofia, Bulgaria'],['2004','Summer School of Democracy','Friedrich Ebert Foundation, Berlin']]},
    contact:{k:'Professional profiles',h:'Contact',intro:'For interviews, speaking engagements and expert commentary.',location:'Astana, Kazakhstan',note:'Please get in touch via Telegram or LinkedIn.',cv:'Download CV',cvnote:'Russian and English CVs will be added after the website’s final review.'},footer:'© 2026 Gaziz Abishev. Personal website.'
  }
};

const links={telegram:'https://t.me/gaziz1984',linkedin:'https://www.linkedin.com/in/gaziz-abishev-8943427a/',facebook:'https://www.facebook.com/ags1984kz',instagram:'https://www.instagram.com/abishevanalytics/',youtube:'https://www.youtube.com/@NeQuryltay',youtube2:'https://www.youtube.com/c/GazizAbishev',scholar:'https://scholar.google.com/citations?user=vHin4XMAAAAJ',oxford:'https://www.ongc.ox.ac.uk/people/gaziz-abishev'};
const reportUrl='https://api.kipd.kz/storage/uploads/images/2023/12/27/%D0%9F%D0%BE%D0%BB%D0%B8%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9%20%D0%B0%D1%81%D0%BF%D0%B5%D0%BA%D1%82%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B%20%D0%BD%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B3%D0%BE%20%D0%BA%D1%83%D1%80%D1%83%D0%BB%D1%82%D0%B0%D1%8F_1703676377.pdf';
const ext=(href,label)=>`<a href="${href}" target="_blank" rel="noopener">${label} ↗</a>`;
function render(lang){
 const d=DATA[lang]; document.documentElement.lang=lang; document.title=d.title; document.querySelector('meta[name=description]').content=d.description;
 document.querySelectorAll('[data-set-lang]').forEach(b=>b.classList.toggle('active',b.dataset.setLang===lang));
 const nav=document.querySelector('#nav'); nav.innerHTML=d.nav.map(([id,label])=>`<a href="#${id}">${label}</a>`).join(''); document.querySelector('.menu-toggle').textContent=d.menu;
 const edu=d.education.items.map(x=>`<article class="card reveal"><span class="year">${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('');
 const exp=d.experience.items.map(x=>`<article class="timeline-item reveal"><span class="date">${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('');
 const pub=d.public.items.map(x=>`<article class="role reveal"><span class="date">${x[0]}</span><h3>${x[1]}</h3></article>`).join('');
 const papers=d.research.publications.map(x=>`<article class="publication reveal"><div class="pub-year">${x[0]}</div><div><h3>${x[1]}</h3><p>${x[2]}</p><p><em>${x[3]}</em></p></div>${ext(x[4],d.research.doi)}</article>`).join('');
 const media=d.media.items.map(x=>`<article class="media-card reveal"><span class="eyebrow">${x[2]}</span><h3>${x[0]}</h3><p>${x[1]}</p>${ext(x[3],x[2])}</article>`).join('');
 const awards=d.awards.items.map(x=>`<article class="award reveal"><span class="year">${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('');
 const facts=d.about.facts.map(x=>`<div><dt>${x[0]}</dt><dd>${x[1]}</dd></div>`).join('');
 const specs=d.about.spec.map(x=>`<div class="specialty reveal">${x}</div>`).join('');
 document.querySelector('#main').innerHTML=`
 <section id="top" class="hero"><div class="hero-copy"><span class="eyebrow">${d.hero.eyebrow}</span><h1>${d.hero.name}</h1><div class="lead">${d.hero.lead}</div><p class="hero-note">${d.hero.note}</p><div class="hero-actions"><a class="btn primary" href="#about">${d.hero.about}</a><a class="btn" href="#research">${d.hero.research}</a></div></div><div class="hero-photo"><img src="assets/gaziz-abishev.webp" alt="${d.hero.name}" width="853" height="1280"></div></section>
 <section id="about" class="section"><div class="section-head reveal"><div><div class="kicker">${d.about.k}</div><h2>${d.about.h}</h2></div><p class="section-intro">${d.about.intro}</p></div><div class="about-grid"><div class="prose reveal"><p>${d.about.p1}</p><p>${d.about.p2}</p></div><dl class="facts reveal">${facts}</dl></div><div class="specialties">${specs}</div></section>
 <section id="education" class="section"><div class="section-head reveal"><div><div class="kicker">${d.education.k}</div><h2>${d.education.h}</h2></div><p class="section-intro">${d.education.intro}</p></div><div class="cards">${edu}</div></section>
 <section id="experience" class="section dark"><div class="section-head reveal"><div><div class="kicker">${d.experience.k}</div><h2>${d.experience.h}</h2></div><p class="section-intro">${d.experience.intro}</p></div><div class="timeline">${exp}</div></section>
 <section id="public" class="section wine"><div class="section-head reveal"><div><div class="kicker">${d.public.k}</div><h2>${d.public.h}</h2></div><p class="section-intro">${d.public.intro}</p></div><div class="roles">${pub}</div></section>
 <section id="research" class="section"><div class="section-head reveal"><div><div class="kicker">${d.research.k}</div><h2>${d.research.h}</h2></div><p class="section-intro">${d.research.intro}</p></div>${papers}<div class="report reveal"><div><div class="kicker">${d.research.reportLabel}</div><h3>${d.research.report}</h3><p>${d.research.reportMeta}</p></div>${ext(reportUrl,d.research.reportLink)}</div><p style="margin-top:30px">${ext(links.scholar,d.research.scholar)} &nbsp; · &nbsp; ${ext(links.oxford,'Oxford profile')}</p></section>
 <section id="media" class="section dark"><div class="section-head reveal"><div><div class="kicker">${d.media.k}</div><h2>${d.media.h}</h2></div><p class="section-intro">${d.media.intro}</p></div><div class="media-grid">${media}</div></section>
 <section id="awards" class="section dark"><div class="section-head reveal"><div><div class="kicker">${d.awards.k}</div><h2>${d.awards.h}</h2></div><p class="section-intro">${d.awards.intro}</p></div><div class="awards">${awards}</div></section>
 <section id="skills" class="section"><div class="section-head reveal"><div><div class="kicker">${d.skills.k}</div><h2>${d.skills.h}</h2></div></div><div class="languages-training"><div><h3>${d.skills.languages}</h3><ul class="simple-list">${d.skills.langs.map(x=>`<li><strong>${x[0]}</strong>${x[1]}</li>`).join('')}</ul></div><div><h3>${d.skills.training}</h3><ul class="simple-list">${d.skills.courses.map(x=>`<li><strong>${x[0]} · ${x[1]}</strong>${x[2]}</li>`).join('')}</ul></div></div></section>
 <section id="contact" class="section"><div class="section-head reveal"><div><div class="kicker">${d.contact.k}</div><h2>${d.contact.h}</h2></div><p class="section-intro">${d.contact.intro}</p></div><div class="contact-grid"><div class="contact-card"><h3>${d.contact.location}</h3><p class="contact-note">${d.contact.note}</p><div class="socials">${[['Telegram',links.telegram],['LinkedIn',links.linkedin],['Facebook',links.facebook],['Instagram',links.instagram],['NeQurultay',links.youtube],['YouTube',links.youtube2]].map(x=>ext(x[1],x[0])).join('')}</div></div><div class="contact-card"><h3>${d.contact.cv}</h3><p class="contact-note">${d.contact.cvnote}</p><span class="btn" aria-disabled="true">PDF · soon</span></div></div></section>`;
 document.querySelector('#footer').innerHTML=`<span>${d.footer}</span><span>${ext(links.telegram,'ABISHEV ANALYTICS')}</span>`;
 localStorage.setItem('siteLang',lang); setupReveal();
}
function setupReveal(){const els=document.querySelectorAll('.reveal'); if(!('IntersectionObserver'in window)){els.forEach(e=>e.classList.add('visible'));return} const io=new IntersectionObserver(entries=>entries.forEach(x=>{if(x.isIntersecting){x.target.classList.add('visible');io.unobserve(x.target)}}),{threshold:.08});els.forEach(e=>io.observe(e))}
document.querySelectorAll('[data-set-lang]').forEach(b=>b.addEventListener('click',()=>render(b.dataset.setLang)));
document.querySelector('.menu-toggle').addEventListener('click',e=>{const nav=document.querySelector('#nav');nav.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',nav.classList.contains('open'))});
document.querySelector('#nav').addEventListener('click',()=>document.querySelector('#nav').classList.remove('open'));
render(localStorage.getItem('siteLang')||'ru');
